defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  verbose: false

# HPC connection settings
hpc:
  host: ${oc.env:HPC_HOST,hpc.address.example}  # HPC server hostname, override with HPC_HOST env var
  user: ${oc.env:HPC_USER,username}   # Can be overridden with HPC_USER env var
  port: 22                 # SSH port

# Sync settings
sync:
  source_dir: "${hydra:runtime.cwd}"  # Current working directory
  target_dir: ${oc.env:HPC_TARGET_DIR,/target/directory/example}  # Override with HPC_TARGET_DIR env var
  exclude:
    - "**/.git"        # Exclude all .git directories
    - "**/.git/**"     # Exclude all contents of .git directories
    - "__pycache__/"
    - "*.pyc"
    - ".env"
    - ".venv/"
    - ".pytest_cache/"
    - ".coverage"
    - ".ruff_cache/"
    - "*.egg-info/"
  
  # Additional rsync options
  options:
    - "--archive"      # Preserve permissions, timestamps, etc.
    - "--compress"     # Compress data during transfer
    - "--verbose"      # Show detailed progress
    - "--delete"       # Delete files in target that don't exist in source 
    - "-P"             # Show progress of transfer